### ISSUE TITLE
Cannot read property 'Defferd' of undefined

### ISSUE THREAD

**Issue by mensmaximus** [webcreate/infinite-ajax-scroll#271]
I was just testing IAS for a project based on WordPress 4.7.2. After loading IAS I get the following message in the developer console:

Uncaught TypeError: Cannot read property 'Deferred' of undefined
    at IASCallbacks.fireWith (jquery-ias.min.js?ver=4.7.2:13)
    at c.fire (jquery-ias.min.js?ver=4.7.2:13)
    at c.initialize (jquery-ias.min.js?ver=4.7.2:13)
    at HTMLDocument.d (jquery.js?ver=1.12.4:2)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)
fireWith @ jquery-ias.min.js?ver=4.7.2:13
fire @ jquery-ias.min.js?ver=4.7.2:13
c.initialize @ jquery-ias.min.js?ver=4.7.2:13
d @ jquery.js?ver=1.12.4:2
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
ready @ jquery.js?ver=1.12.4:2
K @ jquery.js?ver=1.12.4:2

This happens even if I do not load any extensions by simply initializing IAS.

The current config is:
var ias = $.ias({
        container: "#wpf_search_results",
        item: "article",
        pagination: ".wpf-post-navigation",
        next: "div.wpf-post-navigation a:last",
    });

    ias.extension(new IASTriggerExtension({offset: 2}));
    ias.extension(new IASSpinnerExtension());
    ias.extension(new IASNoneLeftExtension());

**Comment by mensmaximus** [comment]
Got it. IAS requires jQuery 2. To bad WordPress still uses jQuery 1 and loading both versions is to expensive.

**Comment by mensmaximus** [comment]
Well the issue seems to stem from noConflict mode. If I set jQuery.noConflict(); IAS stops working even with jQuery2.

**Comment by mensmaximus** [comment]
Sorted it out. Looking into the thread https://github.com/webcreate/infinite-ajax-scroll/issues/188 I found the minified version of IAS still contains $.Deferred.

Trying to load jquery-ias.js throw the error "Uncaught ReferenceError: IASCallbacks is not defined".

So I decided to change $.Deferred to jQuery.Deferred in jquery-ias.min.js. Now it is working in WordPress 4.7.2 with jQuery 1.12.x.

If you fix that millions of WordPress users could use your script which has some nice advantages over the competing and mostly outdated infinite scroll scripts. And as soon as this is fixed I will buy a license.

**Comment by davemercado** [comment]
hi mensmaximus,

I also had the same issue (**Uncaught TypeError: $.Deferred is not a function**) after applying IAS on my clients website.

I also changed **$.Deferred to jQuery.Deferred in jquery-ias.min.js** like you did and it worked!

Thank you for your input!

**Comment by fieg** [comment]
Hm, I find this a bit strange, as the `$` variable should be scoped. I do indeed think it has something to do with noConflict, but any help would be appreciated. Perhaps someone can find a way to reproduce this on something like jsFiddle?

**Comment by mensmaximus** [comment]
@fieg you realized I talk about the minified version from http://infiniteajaxscroll.com/jquery-ias.min.js ? Although its version shows 2.2.2 it seems not to be scoped as jquery-ias.js and callback.js here on github are.

**Comment by fieg** [comment]
Oh my god! The minimalizer must be ignoring the $ var somehow. *mind blown*

**Comment by fieg** [comment]
Hi, I release a new version v2.2.3 which fixes this issue. You can download it here: https://infiniteajaxscroll.com/download.html

Thank you for you time to report this issue. Please reopen this issue if you believe the issue is not fixed in the new version.

ps. it wasn't the minimalizer after all 😬
