### ISSUE TITLE
infinite-ajax-scroll not working with jQuery 1.11+

### ISSUE THREAD

**Issue by bezbeli** [webcreate/infinite-ajax-scroll#172]
Would be good if ias would work with jQuery 1.11.1 as Wordpress is now using it.

**Comment by fieg** [comment]
Can you give an example of what's not working? I have some tests in place that test against 1.11.* and they seem to work: https://travis-ci.org/webcreate/infinite-ajax-scroll/jobs/43522445

**Comment by bezbeli** [comment]
I have it on my local dev server so I can't give you live example. If I leave wordpress to load its default jQuery (1.11.1 at the moment) I get "Uncaught TypeError: undefined is not a function". This is fine though when jQuery 1.9.1 is loaded. Is there anything that I'm missing here? I disabled all other libs that could possibly conflict, so just jQuery and ias minified are loaded.

**Comment by fieg** [comment]
Perhaps it's related to this: https://github.com/webcreate/infinite-ajax-scroll/blob/master/doc/support.md#uncaught-error-syntax-error-unrecognized-expression?

A live example would definitely help to debug this from my side.

**Comment by bezbeli** [comment]
I could setup wordpress with some fake posts somewhere, I'll try to do it today and get back to you with the link and admin access.

**Comment by bezbeli** [comment]
Hi, I've just sent you l/p for test wordpress, look at functions file in twentyfifteen theme lines 219,220. jQuery 1.11.1 is deregistered now and 1.9.1 is enqueued, posts are loaded as they should. If you comment these lines and load default jQuery it breaks.

**Comment by fieg** [comment]
I don't think I can access your theme files. Can you set jQuery to 1.11.1?

**Comment by bezbeli** [comment]
I think you should be able to access functions through theme editor, but
nevermind I just switched to 1.11.1

e

On 16 January 2015 at 11:34, Jeroen Fiege <notifications@github.com> wrote:

> I don't think I can access your theme files. Can you set jQuery to 1.11.1?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webcreate/infinite-ajax-scroll/issues/172#issuecomment-70235738>
> .
>



-- 
Enes Huseinčehajić
tel: +387 61 221 380
email: bezbeli@gmail.com
web: www.bezbeli.ba

**Comment by fieg** [comment]
Btw, you are mixing v1.x options with the v2.x version of IAS:

    $(document).ready(function() {
        jQuery.ias({
            container : '.site-main',
            item: '.post',
            pagination: '.nav-links',
            next: '.next',
            loader: '<img src="http://vidi.ba/wp-content/themes/twentyfifteen/images/loader.gif"/>',
            triggerPageThreshold: 3
        });
    });

`loader` and `triggerPageThreshold` are no longer available and are replaced by the spinner extension and the trigger extension.

**Comment by fieg** [comment]
I think jQuery is running in noConflict mode. Can you try to replace 

    $(document).ready(function() {

with 

jQuery(document).ready(function() {

**Comment by bezbeli** [comment]
ok so that was where I made mistake
jQuery(document).ready(function() { works just fine now, also I'll check new extensions, thank you very much Fieg

**Comment by fieg** [comment]
No problem, happy to help.
